Feat/wiki
Sirimangalo/meditation-plus-server pull request #122
Opened 2017-01-04 20:28 UTC by olastor

Backend for video wiki

2017-01-04 20:30 UTC, olastor commented
```
/home/travis/build/Sirimangalo/meditation-plus-server/src/config/gulpfile.conf.js
  29:23  error  Expected indentation of 2 spaces but found 22  indent
  30:23  error  Expected indentation of 2 spaces but found 22  indent
```
@binarious Do you know how to fix this?

2017-01-04 20:41 UTC, binarious commented
Should be fixed in https://github.com/Sirimangalo/meditation-plus-server/pull/122/commits/ce5d6278a94349299732bf02007111253b4ee902.

2017-01-13 16:49 UTC, binarious requested changes

2017-01-13 16:49 UTC, binarious commented on src/app/routes/_wiki.router.js
> +    const regExp = /^.*(youtu\.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
This doesn't support `youtube.com` links. Only `youtu.be`. Is this intentioally?

2017-01-13 16:49 UTC, binarious commented on src/app/routes/_wiki.router.js
> +  router.post('/api/wiki', async (req, res, next) => {
Huge function. Maybe split into smaller ones?

2017-01-14 18:47 UTC, olastor commented on src/app/routes/_wiki.router.js
> +    const regExp = /^.*(youtu\.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
It should support all sorts of link types. The regexp `youtube\.be` is optional there.
See: http://stackoverflow.com/a/8260383

2017-04-20 16:43 UTC, closed without merging