Feat/analytics
Sirimangalo/meditation-plus-server pull request #128
Opened 2017-03-21 17:15 UTC by olastor

2017-03-21 17:49 UTC, binarious commented on src/app/routes/_analytics.router.js
> +        const minObjID = ObjectId(Math.floor(dtStart / 1000).toString(16) + "0000000000000000");
Could you please explain this a bit in detail?

2017-03-21 17:50 UTC, binarious requested changes
Please add basic tests for the analytics routes (you can copy existing ones) and fix the linting issues.

2017-03-21 18:47 UTC, olastor commented on src/app/routes/_analytics.router.js
> +        const minObjID = ObjectId(Math.floor(dtStart / 1000).toString(16) + "0000000000000000");
http://stackoverflow.com/questions/6452021/getting-timestamp-from-mongodb-id The first 4 Bytes of a MongoDB id contain a timestamp of the creation. That means when an object id is greater than another one is, its creation datetime of the first one has to be after (or at the same time) the creation of the second one.

2017-03-22 19:35 UTC, binarious commented on src/app/routes/_analytics.router.js
> +        const minObjID = ObjectId(Math.floor(dtStart / 1000).toString(16) + "0000000000000000");
Thank you for the clarification.

2017-03-24 17:21 UTC, binarious approved these changes

2017-03-24 17:22 UTC, merged