Feat/push api
Sirimangalo/meditation-plus-server pull request #131
Opened 2017-03-30 15:06 UTC by olastor

Implementing Push Notifications for Firefox and Chrome

Need to set correct  "gcm_sender_id" before merge.

@binarious Should I try implementing Safari as well?

2017-03-30 15:10 UTC, binarious requested changes
Great work! Some minor things though.

2017-03-30 15:10 UTC, binarious commented on src/app/helper/youtube.js
> -        key: process.env.YOUTUBE_API_KEY
Please rename this in the README, too.

2017-03-30 15:10 UTC, binarious commented on src/app/routes/_message.router.js
> +
Why?

2017-03-30 15:10 UTC, binarious commented on src/app/routes/_push.router.js
> +      const subscription = await PushSubscriptions.findOne({
Isn't there a subscription for every user? Why `findOne` then?

2017-03-30 15:20 UTC, olastor commented on src/app/routes/_push.router.js
> +      const subscription = await PushSubscriptions.findOne({
The endpoint url is unique for every session, if that's what you mean.

2017-04-18 19:47 UTC, binarious approved these changes

2017-04-21 16:23 UTC, merged