feat: reintroduce usernames
Sirimangalo/meditation-plus-server pull request #136
Opened 2017-05-07 09:45 UTC by binarious

Please test this locally.

2017-05-07 11:55 UTC, olastor requested changes
The server crashes (locally) if I try to sign up a new account and choose an existing name (not the username): `error: uncaughtException: insertDocument :: caused by :: 11000 E11000 duplicate key error index: test.users.$name_1  dup key: { : "Sebastian23" }`

That's some weird behaviour, can you reproduce it?

2017-05-07 11:55 UTC, olastor commented on src/config/passport.conf.js
>    let bounds = {
The minimum email length of 5 characters prevents someone with a shorter username to login.

2017-05-07 11:55 UTC, olastor commented on src/config/passport.conf.js
> +          if (!req.body.username || reservedUsernames.contains(req.body.username)) {
Throws a Type Error for me? I don't know a `Array.contains()` method, did you mean `reservedUsernames.indexOf(req.body.username) !== -1`

2017-05-07 11:55 UTC, olastor commented on src/config/passport.conf.js
> +        if (user || reservedUsernames.contains(req.body.username) ) {
same thing as below

2017-05-07 11:55 UTC, olastor commented on src/config/passport.conf.js
> +const reservedUsernames = ['yuttadhammo', 'doug', 'martin', 'robin', 'sebastian', 'it'];
good idea! the username `it` can't be used with the current validation (username must be longer than 3 chars), though.

2017-05-07 12:04 UTC, binarious commented on src/config/passport.conf.js
> +          if (!req.body.username || reservedUsernames.contains(req.body.username)) {
Whoops, I meant [includes](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/includes). Will fix it.

2017-05-07 12:05 UTC, binarious commented
@olastor Can you try it with a fresh database?

2017-05-07 12:16 UTC, olastor commented
@binarious Ok worked now.

2017-05-08 18:40 UTC, binarious commented
@olastor Things should be fixed.

2017-05-09 12:42 UTC, binarious commented
@olastor Tests are still failing and I can't finde the error at the moment. Could you take a look?

2017-05-09 14:07 UTC, olastor commented
@binarious I'll try to solve it.

2017-05-09 14:51 UTC, olastor approved these changes

2017-05-09 14:53 UTC, merged