feat(routes): add a simple status page
Sirimangalo/meditation-plus-server pull request #151
Opened 2017-06-12 16:31 UTC by binarious

Closes https://github.com/Sirimangalo/meditation-plus-angular/issues/489

2017-06-15 17:38 UTC, jiixing commented
Should it access mongodb to check the connection, as current hanging issue is caused by the db connection going down

2017-06-15 17:57 UTC, olastor commented
`mongoose.connection.readyState` should work (see https://stackoverflow.com/a/19606067), shouldn't it?

2017-06-15 17:59 UTC, olastor requested changes
Checking MongoDB connection would be useful. `mongoose.connection.readyState` should work (see https://stackoverflow.com/a/19606067), shouldn't it?

2017-06-20 12:01 UTC, olastor requested changes
Can you please add a check for mongodb status as well?

2017-06-20 12:01 UTC, olastor commented on src/app/routes.js
> +  router.get('/status', (req, res) => {
Do you have to be logged in to request this? Is there a frontend page or are you supposed to check this with i.e. `curl`?

2017-06-21 00:27 UTC, jiixing commented on src/app/routes.js
> +  router.get('/status', (req, res) => {
I think the plan is to use 3rd party ping service like uptimerobot to check the health of the db connection, and get email notification if the connection died

2017-07-05 16:20 UTC, binarious commented
The mongoose check has been added.

2017-07-07 10:58 UTC, olastor approved these changes

2017-07-12 16:20 UTC, merged