Refactor/appointment notify
Sirimangalo/meditation-plus-server pull request #167
Opened 2017-08-27 18:02 UTC by olastor

2017-08-28 17:35 UTC, binarious requested changes

2017-08-28 17:35 UTC, binarious commented on src/scripts/appointment-notify.js
> +  const now = moment.tz('America/Toronto');
Another PR made this configurable, didn't it?

2017-08-28 17:35 UTC, binarious commented
Please resolve the conflicts.

2017-08-31 06:04 UTC, olastor commented
Conflicts should be resolved

2017-09-03 12:25 UTC, olastor commented
Need to rewrite this a bit. Please don't merge yet

2017-09-03 16:17 UTC, binarious approved these changes

2017-09-03 16:17 UTC, merged