Refactor/profile stats
Sirimangalo/meditation-plus-server pull request #51
Opened 2016-09-18 08:07 UTC by binarious

Removed complex profile calculation to a separate class.

2016-09-21 11:36 UTC, olastor requested changes
One thing which is maybe worth of opening a new issue: Sessions which 'overflow' a day (i.e. 60min from 23:30 to 00:30 the following day) will be listed only on the day they were started. Maybe this could cause problems for users from different timezones.

2016-09-21 11:36 UTC, olastor commented on src/app/helper/profile.js
> +    let tenWeeksAgo = moment(todayWithoutTime).subtract(9, 'weeks');
do you mean `.substract(10, 'weeks').add(1, 'day')`? Same thing for the next line

2016-09-21 11:36 UTC, olastor commented on src/app/helper/profile.js
> +        meditations.currentConsecutiveDays = 1;
When a user has no meditation entry today or the day before, `meditations.currentConsecuteDays` will still be 1. I think consecutive days should mean if you have no recent meditation log, then this means 0 consecutive days.

2016-10-03 16:08 UTC, binarious commented
@olastor please re-check. Does it work for you?

2016-10-04 06:43 UTC, binarious commented on src/app/helper/profile.js
> +    let tenWeeksAgo = moment(todayWithoutTime).subtract(9, 'weeks');
No, because the current week and month is included..

2016-10-04 07:05 UTC, binarious commented
@olastor It works for me. Can you check, too, please?

2016-10-05 12:33 UTC, olastor approved these changes

2016-10-05 19:17 UTC, merged